export interface OfflineMedicineRecord {
  name: string;
  aliases: string[];
  genericName: string;
  commonUses: string;
  warnings: string;
  sideEffects: string[];
  estimatedPrice: string;
  philHealthCovered: boolean;
}

// This JSON is generated by scripts/kaggle_to_offline_json.py.
// Keep this file present (can be an empty array) so bundling remains stable.
// Load lazily to avoid blocking app startup with 4.6 MB JSON

let GENERATED_OFFLINE_MEDICINES: OfflineMedicineRecord[] | null = null;
let ALL_OFFLINE_MEDICINES_CACHE: OfflineMedicineRecord[] | null = null;

function loadGeneratedMedicines(): OfflineMedicineRecord[] {
  if (GENERATED_OFFLINE_MEDICINES === null) {
    try {
      GENERATED_OFFLINE_MEDICINES =
        require("../assets/data/offline-medicines.generated.json") as OfflineMedicineRecord[];
    } catch (error) {
      console.warn("Failed to load offline medicines from JSON:", error);
      GENERATED_OFFLINE_MEDICINES = [];
    }
  }
  return GENERATED_OFFLINE_MEDICINES;
}

function loadAllOfflineMedicines(): OfflineMedicineRecord[] {
  if (ALL_OFFLINE_MEDICINES_CACHE === null) {
    ALL_OFFLINE_MEDICINES_CACHE = [
      ...OFFLINE_MEDICINES,
      ...loadGeneratedMedicines(),
    ];
  }

  return ALL_OFFLINE_MEDICINES_CACHE;
}

// Replace or expand this list with your Kaggle-exported JSON dataset for richer offline behavior.
export const OFFLINE_MEDICINES: OfflineMedicineRecord[] = [
  {
    name: "Paracetamol",
    aliases: ["biogesic", "acetaminophen", "tylenol"],
    genericName: "Paracetamol",
    commonUses: "Fever and mild pain relief",
    warnings: "Do not exceed max daily dose. Avoid combining with alcohol.",
    sideEffects: ["Nausea", "Rash (rare)", "Liver injury in overdose"],
    estimatedPrice: "PHP 4-8 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Amoxicillin",
    aliases: ["amox", "amoxil"],
    genericName: "Amoxicillin",
    commonUses: "Bacterial infections",
    warnings: "Complete full course. Not for viral infections.",
    sideEffects: ["Diarrhea", "Nausea", "Rash"],
    estimatedPrice: "PHP 12-25 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Amlodipine",
    aliases: ["norvasc"],
    genericName: "Amlodipine",
    commonUses: "High blood pressure and angina",
    warnings: "May cause dizziness when standing.",
    sideEffects: ["Ankle swelling", "Headache", "Flushing"],
    estimatedPrice: "PHP 6-18 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Metformin",
    aliases: ["glucophage"],
    genericName: "Metformin",
    commonUses: "Type 2 diabetes blood sugar control",
    warnings: "Take with food to reduce stomach upset.",
    sideEffects: ["Nausea", "Diarrhea", "Abdominal discomfort"],
    estimatedPrice: "PHP 5-15 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Losartan",
    aliases: ["cozaar"],
    genericName: "Losartan",
    commonUses: "High blood pressure and kidney protection",
    warnings: "Monitor blood pressure regularly.",
    sideEffects: ["Dizziness", "Fatigue", "High potassium"],
    estimatedPrice: "PHP 8-22 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Aspirin",
    aliases: ["acetylsalicylic acid"],
    genericName: "Aspirin",
    commonUses: "Pain relief and antiplatelet use",
    warnings: "Can increase bleeding risk and irritate stomach.",
    sideEffects: ["Stomach pain", "Bleeding", "Heartburn"],
    estimatedPrice: "PHP 3-10 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Warfarin",
    aliases: ["coumadin"],
    genericName: "Warfarin",
    commonUses: "Blood clot prevention",
    warnings: "High interaction risk. Monitor INR.",
    sideEffects: ["Bleeding", "Bruising", "Nausea"],
    estimatedPrice: "PHP 20-45 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Ibuprofen",
    aliases: ["advil", "medicol", "brufen"],
    genericName: "Ibuprofen",
    commonUses: "Pain, inflammation, and fever",
    warnings:
      "Take after meals. Avoid with ulcer or kidney disease unless prescribed.",
    sideEffects: ["Stomach pain", "Heartburn", "Nausea"],
    estimatedPrice: "PHP 6-15 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Omeprazole",
    aliases: ["losec", "omac"],
    genericName: "Omeprazole",
    commonUses: "Acid reflux and ulcer treatment",
    warnings:
      "Usually taken before meals. Long-term use should be reviewed by doctor.",
    sideEffects: ["Headache", "Abdominal pain", "Diarrhea"],
    estimatedPrice: "PHP 10-28 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Cetirizine",
    aliases: ["zyrtec", "allertec"],
    genericName: "Cetirizine",
    commonUses: "Allergy relief",
    warnings: "May cause drowsiness in some users.",
    sideEffects: ["Drowsiness", "Dry mouth", "Fatigue"],
    estimatedPrice: "PHP 8-18 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Simvastatin",
    aliases: ["zocor"],
    genericName: "Simvastatin",
    commonUses: "Lowering cholesterol",
    warnings:
      "Usually taken at night. Avoid grapefruit unless advised otherwise.",
    sideEffects: ["Muscle pain", "Headache", "Nausea"],
    estimatedPrice: "PHP 9-25 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Salbutamol",
    aliases: ["ventolin", "asmalin"],
    genericName: "Salbutamol",
    commonUses: "Relief of asthma and bronchospasm",
    warnings: "Use as directed. Overuse may cause fast heartbeat.",
    sideEffects: ["Tremors", "Palpitations", "Headache"],
    estimatedPrice: "PHP 12-35 per tablet / inhaler varies",
    philHealthCovered: false,
  },
  {
    name: "Sambong",
    aliases: ["re-leaf", "blumea balsamifera", "sambong capsule"],
    genericName: "Sambong Leaf",
    commonUses: "Diuretic, kidney stones, hypertension",
    warnings: "Ensure adequate water intake. Consult doctor if pregnant.",
    sideEffects: ["Stomach pain", "Allergic reaction (rare)"],
    estimatedPrice: "PHP 6-12 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Tamsulosin",
    aliases: ["tamsulosine", "profloxin", "harnal", "contiflo"],
    genericName: "Tamsulosin HCl",
    commonUses: "Benign Prostatic Hyperplasia (BPH), difficulty urinating",
    warnings: "Take 30 mins after the same meal daily. May cause dizziness.",
    sideEffects: ["Dizziness", "Ejaculation problems", "Runny nose"],
    estimatedPrice: "PHP 25-45 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Ciprofloxacin",
    aliases: ["ciprobay", "cipro"],
    genericName: "Ciprofloxacin",
    commonUses: "Bacterial infections (UTI, skin, lung)",
    warnings: "Finish full course. Avoid dairy/antacids 2 hours before/after.",
    sideEffects: ["Nausea", "Diarrhea", "Tendon pain (rare)"],
    estimatedPrice: "PHP 15-35 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Co-Amoxiclav",
    aliases: ["augmentin", "natravox"],
    genericName: "Amoxicillin + Clavulanic Acid",
    commonUses: "Bacterial infections (respiratory, ear, skin)",
    warnings: "Finish full course. Take with food to reduce stomach upset.",
    sideEffects: ["Diarrhea", "Nausea", "Vomiting"],
    estimatedPrice: "PHP 25-60 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Celecoxib",
    aliases: ["celebrex", "celcoxx"],
    genericName: "Celecoxib",
    commonUses: "Arthritis, pain relief, inflammation",
    warnings: "Heart risk warning. Not for those with sulfa allergy.",
    sideEffects: ["Stomach pain", "Headache", "High blood pressure"],
    estimatedPrice: "PHP 15-40 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Mefenamic Acid",
    aliases: ["ponstan", "dolfenal"],
    genericName: "Mefenamic Acid",
    commonUses: "Mild to moderate pain, menstrual cramps",
    warnings: "Take with food. Do not take for more than 7 days.",
    sideEffects: ["Stomach pain", "Drowsiness", "Nausea"],
    estimatedPrice: "PHP 5-15 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Hyoscine",
    aliases: ["buscopan", "hbb"],
    genericName: "Hyoscine N-butylbromide",
    commonUses: "Stomach cramps, abdominal pain",
    warnings: "May cause dry mouth or blurred vision.",
    sideEffects: ["Dry mouth", "Constipation", "Fast heartbeat"],
    estimatedPrice: "PHP 10-25 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Carbocisteine",
    aliases: ["solmux", "lovir"],
    genericName: "Carbocisteine",
    commonUses: "Cough with phlegm",
    warnings: "Take with food if stomach upset occurs.",
    sideEffects: ["Nausea", "Stomach discomfort"],
    estimatedPrice: "PHP 5-15 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Loperamide",
    aliases: ["diatabs", "imodium"],
    genericName: "Loperamide",
    commonUses: "Acute diarrhea",
    warnings: "Drink plenty of water. Do not use if stool has blood.",
    sideEffects: ["Constipation", "Dizziness", "Drowsiness"],
    estimatedPrice: "PHP 4-10 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Lagundi",
    aliases: ["ascof", "plemex"],
    genericName: "Lagundi Leaf",
    commonUses: "Cough and asthma relief",
    warnings: "Safe for most. Consult doctor if symptoms persist.",
    sideEffects: ["Mild stomach upset (rare)"],
    estimatedPrice: "PHP 5-12 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Aluminum Magnesium Hydroxide",
    aliases: ["kremil-s", "maalox"],
    genericName: "AlMgOH + Simeticone",
    commonUses: "Hyperacidity, heartburn, gas",
    warnings: "Do not take within 2 hours of other meds.",
    sideEffects: ["Chalky taste", "Constipation/Diarrhea"],
    estimatedPrice: "PHP 6-10 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Phenylephrine + Paracetamol",
    aliases: ["neozep", "bioflu", "decolgen"],
    genericName: "Phenylephrine HCl + Chlorphenamine + Paracetamol",
    commonUses: "Colds, fever, runny nose",
    warnings: "May cause drowsiness. Avoid alcohol.",
    sideEffects: ["Drowsiness", "Dry mouth"],
    estimatedPrice: "PHP 6-12 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Moringa",
    aliases: ["malunggay", "natalac"],
    genericName: "Moringa Oleifera",
    commonUses: "Nutritional supplement, lactation aid",
    warnings: "Safe supplement. Consult doctor if pregnant.",
    sideEffects: ["None known"],
    estimatedPrice: "PHP 5-10 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Vitamins B-Complex",
    aliases: ["neurobion", "poly-nerve"],
    genericName: "Vitamin B1 + B6 + B12",
    commonUses: "Nerve health, energy",
    warnings: "Do not exceed recommended dose.",
    sideEffects: ["Bright yellow urine (harmless)"],
    estimatedPrice: "PHP 10-25 per tablet",
    philHealthCovered: false,
  },
];

export const ALL_OFFLINE_MEDICINES: OfflineMedicineRecord[] = OFFLINE_MEDICINES;

export function getOfflineMedicineCount(): number {
  return OFFLINE_MEDICINES.length + getGeneratedOfflineMedicineCount();
}

export function getGeneratedOfflineMedicineCount(): number {
  return loadGeneratedMedicines().length;
}

export function getAllOfflineMedicines(): OfflineMedicineRecord[] {
  return loadAllOfflineMedicines();
}
