export interface OfflineMedicineRecord {
  name: string;
  aliases: string[];
  genericName: string;
  commonUses: string;
  warnings: string;
  sideEffects: string[];
  estimatedPrice: string;
  philHealthCovered: boolean;
  howToTake?: string;
  avoidWith?: string[];
  importantNotes?: string[];
  missedDoseAdvice?: string;
  whenToSeekHelp?: string;
  storage?: string;
}

// This JSON is generated by scripts/kaggle_to_offline_json.py.
// Keep this file present (can be an empty array) so bundling remains stable.
// Load lazily to avoid blocking app startup with 4.6 MB JSON

let GENERATED_OFFLINE_MEDICINES: OfflineMedicineRecord[] | null = null;
let PHILIPPINE_OFFLINE_MEDICINES: OfflineMedicineRecord[] | null = null;
let PHILIPPINE_GENERATED_OFFLINE_MEDICINES: OfflineMedicineRecord[] | null =
  null;
let ALL_OFFLINE_MEDICINES_CACHE: OfflineMedicineRecord[] | null = null;

type OfflineMedicineDetails = Pick<
  OfflineMedicineRecord,
  | "howToTake"
  | "avoidWith"
  | "importantNotes"
  | "missedDoseAdvice"
  | "whenToSeekHelp"
  | "storage"
>;

function normMedicineKey(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\s+-]/g, " ")
    .replace(/\s+/g, " ");
}

const OFFLINE_MEDICINE_DETAILS: Record<string, OfflineMedicineDetails> = {
  "paracetamol": {
    howToTake:
      "Use only the dose written on the label or prescription. Keep at least 4 hours between doses.",
    avoidWith: ["Alcohol", "Other medicines with paracetamol/acetaminophen"],
    importantNotes: [
      "Check cold and flu medicines because many already contain paracetamol.",
      "Extra caution is needed in liver disease or heavy alcohol use.",
    ],
    missedDoseAdvice:
      "Take it when needed only. If it is scheduled, take the missed dose when remembered unless the next dose is near.",
    whenToSeekHelp:
      "Seek urgent help for yellowing of the eyes, severe vomiting, rash with swelling, or suspected overdose.",
    storage: "Store in a cool, dry place away from heat and moisture.",
  },
  "amoxicillin": {
    howToTake:
      "Take exactly as prescribed and finish the full course even if you feel better.",
    avoidWith: ["Self-stopping treatment early"],
    importantNotes: [
      "Missed doses can make treatment less effective.",
      "Tell a clinician if you have a penicillin allergy.",
    ],
    missedDoseAdvice:
      "Take the missed dose as soon as remembered unless the next dose is almost due. Do not double the dose.",
    whenToSeekHelp:
      "Seek care for trouble breathing, facial swelling, severe rash, or persistent severe diarrhea.",
    storage: "Store as directed on the package. Liquid forms may have special storage instructions.",
  },
  "amlodipine": {
    howToTake:
      "Take once daily at the same time each day, with or without food.",
    avoidWith: ["Standing up too quickly if dizzy"],
    importantNotes: [
      "Blood pressure control usually needs regular daily use.",
      "Mild ankle swelling can happen with this medicine.",
    ],
    missedDoseAdvice:
      "Take the missed dose if remembered the same day. Skip it if it is close to the next dose.",
    whenToSeekHelp:
      "Seek help for chest pain, fainting, severe dizziness, or shortness of breath.",
    storage: "Store in a cool, dry place.",
  },
  "metformin": {
    howToTake:
      "Take with food to reduce stomach upset. Swallow extended-release tablets whole.",
    avoidWith: ["Heavy alcohol intake", "Skipping meals repeatedly"],
    importantNotes: [
      "This medicine helps control blood sugar but does not replace diet advice.",
      "Stomach upset is common when starting treatment and often improves.",
    ],
    missedDoseAdvice:
      "Take the missed dose with food when remembered unless it is almost time for the next dose.",
    whenToSeekHelp:
      "Seek care for severe weakness, fast breathing, severe vomiting, or dehydration.",
    storage: "Store in a dry place away from heat.",
  },
  "losartan": {
    howToTake:
      "Take once daily at the same time each day, with or without food.",
    avoidWith: ["Potassium supplements unless prescribed", "Salt substitutes high in potassium"],
    importantNotes: [
      "Regular blood pressure checks are important.",
      "Tell your doctor if you are pregnant or planning pregnancy.",
    ],
    missedDoseAdvice:
      "Take the missed dose when remembered unless the next dose is near. Do not double-dose.",
    whenToSeekHelp:
      "Seek help for fainting, swelling of the face, very low urine output, or severe weakness.",
    storage: "Store in a cool, dry place.",
  },
  "aspirin": {
    howToTake:
      "Take with food or after meals unless your doctor told you otherwise.",
    avoidWith: ["Alcohol", "Other NSAID pain relievers unless advised", "Warfarin or blood thinners without review"],
    importantNotes: [
      "Aspirin can irritate the stomach and raise bleeding risk.",
      "Not all aspirin is for pain relief; some prescriptions are for blood thinning.",
    ],
    missedDoseAdvice:
      "If prescribed once daily for heart protection, take it when remembered on the same day. Skip it if the next dose is near.",
    whenToSeekHelp:
      "Seek urgent care for black stools, vomiting blood, severe stomach pain, or unusual bleeding.",
    storage: "Keep tightly closed in a dry place.",
  },
  "warfarin": {
    howToTake:
      "Take exactly as prescribed at the same time each day. Regular INR monitoring is important.",
    avoidWith: ["Aspirin", "Ibuprofen", "Naproxen", "Sudden large diet changes in leafy greens", "Alcohol binges"],
    importantNotes: [
      "Many medicines and supplements interact with warfarin.",
      "Do not start new herbal products or antibiotics without checking first.",
    ],
    missedDoseAdvice:
      "If you miss a dose, contact your clinic or pharmacist for the safest advice, especially if it is not the same day.",
    whenToSeekHelp:
      "Seek urgent help for bleeding that does not stop, black stools, severe headache, or weakness after a fall.",
    storage: "Store at room temperature away from moisture.",
  },
  "ibuprofen": {
    howToTake:
      "Take after meals or with food to lessen stomach irritation.",
    avoidWith: ["Alcohol", "Other NSAIDs", "Taking it on an empty stomach repeatedly"],
    importantNotes: [
      "Use caution in kidney disease, ulcers, and dehydration.",
      "Longer use may need medical review.",
    ],
    missedDoseAdvice:
      "If used only as needed, take it when needed. If scheduled, skip the missed dose if the next dose is close.",
    whenToSeekHelp:
      "Seek care for black stools, vomiting blood, chest pain, or reduced urine output.",
    storage: "Store in a cool, dry place.",
  },
  "omeprazole": {
    howToTake:
      "Usually take before a meal, often before breakfast. Swallow capsules as directed.",
    avoidWith: ["Taking only after symptoms become severe if it was prescribed daily"],
    importantNotes: [
      "Best results often come after several days of regular use.",
      "Long-term use should be reviewed by a clinician.",
    ],
    missedDoseAdvice:
      "Take the missed dose when remembered unless it is near the next dose.",
    whenToSeekHelp:
      "Seek help for black stools, trouble swallowing, vomiting blood, or unexplained weight loss.",
    storage: "Store away from heat and moisture.",
  },
  "cetirizine": {
    howToTake:
      "Take once daily as directed. Some people prefer taking it at night if it causes drowsiness.",
    avoidWith: ["Alcohol if it makes you sleepy"],
    importantNotes: [
      "It may be less sedating than older antihistamines, but drowsiness can still happen.",
    ],
    missedDoseAdvice:
      "Take the missed dose when remembered if still needed. Skip it if the next dose is near.",
    whenToSeekHelp:
      "Seek help for severe allergic reactions, swelling, or trouble breathing.",
    storage: "Store in a dry place at room temperature.",
  },
  "simvastatin": {
    howToTake:
      "Usually take in the evening or at night if that is how it was prescribed.",
    avoidWith: ["Grapefruit", "Heavy alcohol intake"],
    importantNotes: [
      "Muscle pain should not be ignored, especially with fever or weakness.",
      "Cholesterol treatment works best with regular daily use.",
    ],
    missedDoseAdvice:
      "If remembered the same day, take it then. If the next dose is near, skip the missed dose.",
    whenToSeekHelp:
      "Seek help for severe muscle pain, dark urine, or yellowing of the eyes.",
    storage: "Store at room temperature in a dry place.",
  },
  "salbutamol": {
    howToTake:
      "Use exactly as directed. For inhalers, use the proper inhaler technique.",
    avoidWith: ["Overuse without medical review"],
    importantNotes: [
      "Needing it more often than usual may mean asthma is not well controlled.",
    ],
    missedDoseAdvice:
      "If this is a rescue medicine, use it when symptoms happen. If scheduled, take the next dose as directed.",
    whenToSeekHelp:
      "Seek urgent care for severe breathing difficulty, lips turning blue, or poor relief after repeated rescue doses.",
    storage: "Protect inhalers from extreme heat and direct sunlight.",
  },
  "sambong": {
    howToTake:
      "Use only product directions from a reliable preparation and drink enough water unless a doctor advised fluid restriction.",
    avoidWith: ["Dehydration", "Taking it as a replacement for treatment of severe kidney pain"],
    importantNotes: [
      "Helpful as supportive care only; persistent symptoms still need proper medical review.",
    ],
    missedDoseAdvice:
      "If taken on a schedule, take the next dose as directed. Do not double-dose.",
    whenToSeekHelp:
      "Seek care for fever, severe flank pain, blood in urine, or inability to urinate.",
    storage: "Store based on the product label and keep herbal preparations clean and dry.",
  },
  "tamsulosin hcl": {
    howToTake:
      "Take 30 minutes after the same meal each day to keep the effect steady.",
    avoidWith: ["Standing quickly if dizzy"],
    importantNotes: [
      "This can lower blood pressure and cause lightheadedness.",
      "Tell your eye surgeon if you take this medicine before cataract surgery.",
    ],
    missedDoseAdvice:
      "Take the missed dose later the same day if remembered. If you skip several days, ask your clinician before restarting.",
    whenToSeekHelp:
      "Seek help for fainting, severe dizziness, or a painful erection that will not go away.",
    storage: "Store in a cool, dry place.",
  },
  "ciprofloxacin": {
    howToTake:
      "Take exactly as prescribed and finish the full course. Separate from antacids or dairy by a few hours if instructed.",
    avoidWith: ["Dairy or antacids close to the dose", "Strenuous activity if tendon pain starts"],
    importantNotes: [
      "Ciprofloxacin may affect tendons, especially in older adults.",
      "Use only for confirmed or strongly suspected bacterial infection.",
    ],
    missedDoseAdvice:
      "Take the missed dose when remembered unless the next dose is near. Do not double the dose.",
    whenToSeekHelp:
      "Seek care for tendon pain, severe diarrhea, rash, or numbness/tingling.",
    storage: "Store away from heat and moisture.",
  },
  "amoxicillin clavulanic acid": {
    howToTake:
      "Take with food to reduce stomach upset and finish the full course.",
    avoidWith: ["Stopping treatment early"],
    importantNotes: [
      "This can cause diarrhea; hydration is important.",
    ],
    missedDoseAdvice:
      "Take the missed dose when remembered unless the next dose is near.",
    whenToSeekHelp:
      "Seek care for severe rash, breathing difficulty, or persistent severe diarrhea.",
    storage: "Store as directed on the package.",
  },
  "celecoxib": {
    howToTake:
      "Take as prescribed, with food if it upsets your stomach.",
    avoidWith: ["Other NSAIDs unless advised", "Long-term self-medication"],
    importantNotes: [
      "This may raise heart and stomach risks in some people.",
    ],
    missedDoseAdvice:
      "If used as needed, take it when needed. If scheduled, skip the missed dose if the next dose is near.",
    whenToSeekHelp:
      "Seek help for chest pain, shortness of breath, black stools, or severe swelling.",
    storage: "Store in a dry place at room temperature.",
  },
  "mefenamic acid": {
    howToTake:
      "Take with food or after meals and use for the shortest time needed.",
    avoidWith: ["Other NSAIDs", "Taking longer than prescribed"],
    importantNotes: [
      "This can irritate the stomach and may worsen ulcer symptoms.",
    ],
    missedDoseAdvice:
      "If used only as needed, take it when needed. If scheduled, skip the missed dose if the next dose is near.",
    whenToSeekHelp:
      "Seek care for black stools, vomiting blood, severe stomach pain, or allergic swelling.",
    storage: "Store in a cool, dry place.",
  },
  "hyoscine n butylbromide": {
    howToTake:
      "Take as directed for abdominal cramps. Follow the product label or prescription.",
    avoidWith: ["Using repeatedly for severe unexplained abdominal pain without checkup"],
    importantNotes: [
      "This may cause dry mouth or blurred vision.",
    ],
    missedDoseAdvice:
      "If used only as needed, take it when needed. If scheduled, take the next dose normally.",
    whenToSeekHelp:
      "Seek help for severe abdominal swelling, persistent vomiting, or inability to pass stool or urine.",
    storage: "Store at room temperature away from moisture.",
  },
  "carbocisteine": {
    howToTake:
      "Take with plenty of water unless your doctor told you to limit fluids.",
    avoidWith: ["Using it as a substitute for care when breathing is difficult"],
    importantNotes: [
      "Helps loosen phlegm; it is not an antibiotic.",
    ],
    missedDoseAdvice:
      "Take the missed dose when remembered unless the next dose is near.",
    whenToSeekHelp:
      "Seek care for wheezing, chest pain, high fever, or worsening shortness of breath.",
    storage: "Store in a cool, dry place.",
  },
  "loperamide": {
    howToTake:
      "Use only for short-term diarrhea relief and keep drinking fluids or oral rehydration solution.",
    avoidWith: ["Bloody stool", "High fever", "Long-term self-treatment"],
    importantNotes: [
      "This treats diarrhea symptoms but not the cause.",
    ],
    missedDoseAdvice:
      "This is usually taken as needed, not on a fixed schedule.",
    whenToSeekHelp:
      "Seek care for dehydration, bloody stool, severe abdominal swelling, or diarrhea lasting more than a few days.",
    storage: "Store in a dry place at room temperature.",
  },
  "lagundi": {
    howToTake:
      "Use only according to the product instructions from a reliable preparation.",
    avoidWith: ["Using it instead of medical care for severe breathing problems"],
    importantNotes: [
      "Supportive only; persistent cough still needs proper assessment.",
    ],
    missedDoseAdvice:
      "If taken on schedule, take the next dose normally and do not double-dose.",
    whenToSeekHelp:
      "Seek help for difficulty breathing, chest pain, high fever, or cough lasting unusually long.",
    storage: "Keep in a clean, dry place and follow the label.",
  },
  "almgoh simeticone": {
    howToTake:
      "Take as directed, usually away from other medicines if the label says so.",
    avoidWith: ["Taking it within 2 hours of other medicines without guidance"],
    importantNotes: [
      "It can affect the absorption of some other medicines.",
    ],
    missedDoseAdvice:
      "Usually taken as needed. If prescribed regularly, take the next dose as scheduled.",
    whenToSeekHelp:
      "Seek care for severe abdominal pain, black stools, vomiting blood, or trouble swallowing.",
    storage: "Store at room temperature away from moisture.",
  },
  "phenylephrine hcl chlorphenamine paracetamol": {
    howToTake:
      "Use only as directed on the label and avoid taking other paracetamol-containing cold medicines at the same time.",
    avoidWith: ["Alcohol", "Other paracetamol-containing products"],
    importantNotes: [
      "This combination may cause drowsiness in some people.",
    ],
    missedDoseAdvice:
      "Usually used as needed. If scheduled, skip the missed dose if the next dose is near.",
    whenToSeekHelp:
      "Seek help for palpitations, rash, breathing difficulty, or symptoms that worsen instead of improving.",
    storage: "Store in a cool, dry place.",
  },
  "moringa oleifera": {
    howToTake:
      "Use according to the product label. It should not replace prescribed medicines.",
    avoidWith: ["Using it as a replacement for maintenance medicines without advice"],
    importantNotes: [
      "This is mainly used as a supplement, not as a substitute for full treatment.",
    ],
    missedDoseAdvice:
      "If used on a schedule, take the next dose normally. Do not double-dose.",
    whenToSeekHelp:
      "Seek care if you develop allergic symptoms or worsening medical problems.",
    storage: "Store as directed on the product label.",
  },
  "vitamin b1 b6 b12": {
    howToTake:
      "Take according to the label or prescription, usually after food if it upsets the stomach.",
    avoidWith: ["Taking more than the recommended dose without medical advice"],
    importantNotes: [
      "This supports vitamin intake but is not a quick cure for all nerve symptoms.",
    ],
    missedDoseAdvice:
      "Take the missed dose when remembered unless the next dose is near.",
    whenToSeekHelp:
      "Seek help for persistent numbness, weakness, or worsening nerve pain.",
    storage: "Store in a cool, dry place.",
  },
  "bawang": {
    howToTake:
      "Use according to the preparation label. It should not replace prescribed blood pressure or cholesterol medicines.",
    avoidWith: ["Warfarin", "Other blood thinners without medical advice"],
    importantNotes: [
      "Herbal supplements can still interact with maintenance medicines.",
    ],
    missedDoseAdvice:
      "If taken as a supplement, take the next dose as scheduled and do not double-dose.",
    whenToSeekHelp:
      "Seek help for unusual bleeding, severe stomach pain, or allergic reactions.",
    storage: "Store based on the product label, away from heat and moisture.",
  },
  "tsaang gubat": {
    howToTake:
      "Use only according to the product instructions and continue hydration if used for loose stool support.",
    avoidWith: ["Using it alone for severe diarrhea or dehydration"],
    importantNotes: [
      "This is supportive care only and does not replace treatment for severe infection.",
    ],
    missedDoseAdvice:
      "If taken regularly, take the next dose normally without doubling.",
    whenToSeekHelp:
      "Seek care for blood in stool, severe stomach pain, or dehydration signs.",
    storage: "Store in a clean, dry place.",
  },
  "ampalaya": {
    howToTake:
      "Use only according to the product instructions and monitor blood sugar if you also take diabetes medicines.",
    avoidWith: ["Taking it together with diabetes medicine without watching for low sugar"],
    importantNotes: [
      "It may lower blood sugar and should not replace prescribed diabetes treatment.",
    ],
    missedDoseAdvice:
      "If used on a schedule, take the next dose normally. Do not double-dose.",
    whenToSeekHelp:
      "Seek help for sweating, shakiness, confusion, or fainting from low blood sugar.",
    storage: "Store based on the product label.",
  },
  "yerba buena": {
    howToTake:
      "Use according to the product instructions for minor pain support only.",
    avoidWith: ["Using it as the only treatment for severe or persistent pain"],
    importantNotes: [
      "Persistent headache or tooth pain still needs proper medical or dental care.",
    ],
    missedDoseAdvice:
      "Usually used as needed rather than on a strict schedule.",
    whenToSeekHelp:
      "Seek care for persistent severe pain, swelling, fever, or worsening symptoms.",
    storage: "Store in a clean, dry place.",
  },
  "ulasimang bato": {
    howToTake:
      "Use only according to the product instructions and continue medical follow-up for gout or kidney problems.",
    avoidWith: ["Using it instead of treatment for severe gout attacks or kidney disease"],
    importantNotes: [
      "Supportive only; severe joint pain or fever needs medical review.",
    ],
    missedDoseAdvice:
      "If taken on schedule, take the next dose normally and do not double-dose.",
    whenToSeekHelp:
      "Seek care for fever, severe joint swelling, severe pain, or urine problems.",
    storage: "Store based on the product label.",
  },
  "bayabas": {
    howToTake:
      "Use as directed for supportive wound washing or mouth rinse if the preparation is intended for that purpose.",
    avoidWith: ["Using it as the only treatment for infected wounds"],
    importantNotes: [
      "Supportive care only; infected wounds may still need proper cleaning and antibiotics.",
    ],
    missedDoseAdvice:
      "Usually used as needed rather than on a strict schedule.",
    whenToSeekHelp:
      "Seek care for spreading redness, fever, pus, or worsening pain.",
    storage: "Keep the preparation clean and store as labeled.",
  },
  "akapulko": {
    howToTake:
      "Use only as directed for fungal skin lesions and keep the area clean and dry.",
    avoidWith: ["Applying to badly broken skin or severe irritation without advice"],
    importantNotes: [
      "External supportive use only unless a clinician advised otherwise.",
    ],
    missedDoseAdvice:
      "Apply or use the next dose at the normal time. Do not over-apply.",
    whenToSeekHelp:
      "Seek care for severe redness, swelling, infection signs, or no improvement.",
    storage: "Store based on the product label.",
  },
  "niyog niyogan": {
    howToTake:
      "Use only age-appropriate dosing guidance from a reliable preparation or clinician.",
    avoidWith: ["Taking more than recommended"],
    importantNotes: [
      "Too much may worsen stomach symptoms instead of helping.",
    ],
    missedDoseAdvice:
      "Take the next scheduled dose normally unless a clinician instructed otherwise.",
    whenToSeekHelp:
      "Seek care for severe abdominal pain, repeated vomiting, or dehydration.",
    storage: "Store in a dry place and follow the product label.",
  },
};

function mergeUniqueStrings(primary: string[] = [], secondary: string[] = []) {
  const seen = new Set<string>();
  const merged: string[] = [];

  for (const value of [...primary, ...secondary]) {
    const cleaned = value?.trim();
    if (!cleaned) continue;
    const key = cleaned.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    merged.push(cleaned);
  }

  return merged;
}

function enrichOfflineMedicine(
  medicine: OfflineMedicineRecord,
): OfflineMedicineRecord {
  const detailKeys = [medicine.name, medicine.genericName, ...medicine.aliases]
    .map(normMedicineKey)
    .filter(Boolean);

  const details = detailKeys
    .map((key) => OFFLINE_MEDICINE_DETAILS[key])
    .find(Boolean);

  if (!details) {
    return medicine;
  }

  return {
    ...medicine,
    ...details,
    avoidWith: mergeUniqueStrings(details.avoidWith, medicine.avoidWith),
    importantNotes: mergeUniqueStrings(
      details.importantNotes,
      medicine.importantNotes,
    ),
  };
}

function loadGeneratedMedicines(): OfflineMedicineRecord[] {
  if (GENERATED_OFFLINE_MEDICINES === null) {
    try {
      GENERATED_OFFLINE_MEDICINES =
        (
          require("../assets/data/offline-medicines.generated.json") as OfflineMedicineRecord[]
        ).map(enrichOfflineMedicine);
    } catch (error) {
      console.warn("Failed to load offline medicines from JSON:", error);
      GENERATED_OFFLINE_MEDICINES = [];
    }
  }
  return GENERATED_OFFLINE_MEDICINES;
}

function loadPhilippineMedicines(): OfflineMedicineRecord[] {
  if (PHILIPPINE_OFFLINE_MEDICINES === null) {
    try {
      PHILIPPINE_OFFLINE_MEDICINES =
        (
          require("../assets/data/offline-medicines.philippines.json") as OfflineMedicineRecord[]
        ).map(enrichOfflineMedicine);
    } catch (error) {
      console.warn("Failed to load Philippine offline medicines JSON:", error);
      PHILIPPINE_OFFLINE_MEDICINES = [];
    }
  }
  return PHILIPPINE_OFFLINE_MEDICINES;
}

function loadGeneratedPhilippineMedicines(): OfflineMedicineRecord[] {
  if (PHILIPPINE_GENERATED_OFFLINE_MEDICINES === null) {
    try {
      PHILIPPINE_GENERATED_OFFLINE_MEDICINES =
        (
          require("../assets/data/offline-medicines.ph.generated.json") as OfflineMedicineRecord[]
        ).map(enrichOfflineMedicine);
    } catch (error) {
      console.warn(
        "Failed to load generated Philippine offline medicines JSON:",
        error,
      );
      PHILIPPINE_GENERATED_OFFLINE_MEDICINES = [];
    }
  }
  return PHILIPPINE_GENERATED_OFFLINE_MEDICINES;
}

function loadAllOfflineMedicines(): OfflineMedicineRecord[] {
  if (ALL_OFFLINE_MEDICINES_CACHE === null) {
    ALL_OFFLINE_MEDICINES_CACHE = [
      ...OFFLINE_MEDICINES,
      ...loadPhilippineMedicines(),
      ...loadGeneratedPhilippineMedicines(),
      ...loadGeneratedMedicines(),
    ];
  }

  return ALL_OFFLINE_MEDICINES_CACHE;
}

// Replace or expand this list with your Kaggle-exported JSON dataset for richer offline behavior.
export const OFFLINE_MEDICINES: OfflineMedicineRecord[] = [
  {
    name: "Paracetamol",
    aliases: ["biogesic", "acetaminophen", "tylenol"],
    genericName: "Paracetamol",
    commonUses: "Fever and mild pain relief",
    warnings: "Do not exceed max daily dose. Avoid combining with alcohol.",
    sideEffects: ["Nausea", "Rash (rare)", "Liver injury in overdose"],
    estimatedPrice: "PHP 4-8 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Amoxicillin",
    aliases: ["amox", "amoxil"],
    genericName: "Amoxicillin",
    commonUses: "Bacterial infections",
    warnings: "Complete full course. Not for viral infections.",
    sideEffects: ["Diarrhea", "Nausea", "Rash"],
    estimatedPrice: "PHP 12-25 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Amlodipine",
    aliases: ["norvasc"],
    genericName: "Amlodipine",
    commonUses: "High blood pressure and angina",
    warnings: "May cause dizziness when standing.",
    sideEffects: ["Ankle swelling", "Headache", "Flushing"],
    estimatedPrice: "PHP 6-18 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Metformin",
    aliases: ["glucophage"],
    genericName: "Metformin",
    commonUses: "Type 2 diabetes blood sugar control",
    warnings: "Take with food to reduce stomach upset.",
    sideEffects: ["Nausea", "Diarrhea", "Abdominal discomfort"],
    estimatedPrice: "PHP 5-15 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Losartan",
    aliases: ["cozaar"],
    genericName: "Losartan",
    commonUses: "High blood pressure and kidney protection",
    warnings: "Monitor blood pressure regularly.",
    sideEffects: ["Dizziness", "Fatigue", "High potassium"],
    estimatedPrice: "PHP 8-22 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Aspirin",
    aliases: ["acetylsalicylic acid"],
    genericName: "Aspirin",
    commonUses: "Pain relief and antiplatelet use",
    warnings: "Can increase bleeding risk and irritate stomach.",
    sideEffects: ["Stomach pain", "Bleeding", "Heartburn"],
    estimatedPrice: "PHP 3-10 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Warfarin",
    aliases: ["coumadin"],
    genericName: "Warfarin",
    commonUses: "Blood clot prevention",
    warnings: "High interaction risk. Monitor INR.",
    sideEffects: ["Bleeding", "Bruising", "Nausea"],
    estimatedPrice: "PHP 20-45 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Ibuprofen",
    aliases: ["advil", "medicol", "brufen"],
    genericName: "Ibuprofen",
    commonUses: "Pain, inflammation, and fever",
    warnings:
      "Take after meals. Avoid with ulcer or kidney disease unless prescribed.",
    sideEffects: ["Stomach pain", "Heartburn", "Nausea"],
    estimatedPrice: "PHP 6-15 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Omeprazole",
    aliases: ["losec", "omac"],
    genericName: "Omeprazole",
    commonUses: "Acid reflux and ulcer treatment",
    warnings:
      "Usually taken before meals. Long-term use should be reviewed by doctor.",
    sideEffects: ["Headache", "Abdominal pain", "Diarrhea"],
    estimatedPrice: "PHP 10-28 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Cetirizine",
    aliases: ["zyrtec", "allertec"],
    genericName: "Cetirizine",
    commonUses: "Allergy relief",
    warnings: "May cause drowsiness in some users.",
    sideEffects: ["Drowsiness", "Dry mouth", "Fatigue"],
    estimatedPrice: "PHP 8-18 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Simvastatin",
    aliases: ["zocor"],
    genericName: "Simvastatin",
    commonUses: "Lowering cholesterol",
    warnings:
      "Usually taken at night. Avoid grapefruit unless advised otherwise.",
    sideEffects: ["Muscle pain", "Headache", "Nausea"],
    estimatedPrice: "PHP 9-25 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Salbutamol",
    aliases: ["ventolin", "asmalin"],
    genericName: "Salbutamol",
    commonUses: "Relief of asthma and bronchospasm",
    warnings: "Use as directed. Overuse may cause fast heartbeat.",
    sideEffects: ["Tremors", "Palpitations", "Headache"],
    estimatedPrice: "PHP 12-35 per tablet / inhaler varies",
    philHealthCovered: false,
  },
  {
    name: "Sambong",
    aliases: ["re-leaf", "blumea balsamifera", "sambong capsule"],
    genericName: "Sambong Leaf",
    commonUses: "Diuretic, kidney stones, hypertension",
    warnings: "Ensure adequate water intake. Consult doctor if pregnant.",
    sideEffects: ["Stomach pain", "Allergic reaction (rare)"],
    estimatedPrice: "PHP 6-12 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Tamsulosin",
    aliases: ["tamsulosine", "profloxin", "harnal", "contiflo"],
    genericName: "Tamsulosin HCl",
    commonUses: "Benign Prostatic Hyperplasia (BPH), difficulty urinating",
    warnings: "Take 30 mins after the same meal daily. May cause dizziness.",
    sideEffects: ["Dizziness", "Ejaculation problems", "Runny nose"],
    estimatedPrice: "PHP 25-45 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Ciprofloxacin",
    aliases: ["ciprobay", "cipro"],
    genericName: "Ciprofloxacin",
    commonUses: "Bacterial infections (UTI, skin, lung)",
    warnings: "Finish full course. Avoid dairy/antacids 2 hours before/after.",
    sideEffects: ["Nausea", "Diarrhea", "Tendon pain (rare)"],
    estimatedPrice: "PHP 15-35 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Co-Amoxiclav",
    aliases: ["augmentin", "natravox"],
    genericName: "Amoxicillin + Clavulanic Acid",
    commonUses: "Bacterial infections (respiratory, ear, skin)",
    warnings: "Finish full course. Take with food to reduce stomach upset.",
    sideEffects: ["Diarrhea", "Nausea", "Vomiting"],
    estimatedPrice: "PHP 25-60 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Celecoxib",
    aliases: ["celebrex", "celcoxx"],
    genericName: "Celecoxib",
    commonUses: "Arthritis, pain relief, inflammation",
    warnings: "Heart risk warning. Not for those with sulfa allergy.",
    sideEffects: ["Stomach pain", "Headache", "High blood pressure"],
    estimatedPrice: "PHP 15-40 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Mefenamic Acid",
    aliases: ["ponstan", "dolfenal"],
    genericName: "Mefenamic Acid",
    commonUses: "Mild to moderate pain, menstrual cramps",
    warnings: "Take with food. Do not take for more than 7 days.",
    sideEffects: ["Stomach pain", "Drowsiness", "Nausea"],
    estimatedPrice: "PHP 5-15 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Hyoscine",
    aliases: ["buscopan", "hbb"],
    genericName: "Hyoscine N-butylbromide",
    commonUses: "Stomach cramps, abdominal pain",
    warnings: "May cause dry mouth or blurred vision.",
    sideEffects: ["Dry mouth", "Constipation", "Fast heartbeat"],
    estimatedPrice: "PHP 10-25 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Carbocisteine",
    aliases: ["solmux", "lovir"],
    genericName: "Carbocisteine",
    commonUses: "Cough with phlegm",
    warnings: "Take with food if stomach upset occurs.",
    sideEffects: ["Nausea", "Stomach discomfort"],
    estimatedPrice: "PHP 5-15 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Loperamide",
    aliases: ["diatabs", "imodium"],
    genericName: "Loperamide",
    commonUses: "Acute diarrhea",
    warnings: "Drink plenty of water. Do not use if stool has blood.",
    sideEffects: ["Constipation", "Dizziness", "Drowsiness"],
    estimatedPrice: "PHP 4-10 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Lagundi",
    aliases: ["ascof", "plemex"],
    genericName: "Lagundi Leaf",
    commonUses: "Cough and asthma relief",
    warnings: "Safe for most. Consult doctor if symptoms persist.",
    sideEffects: ["Mild stomach upset (rare)"],
    estimatedPrice: "PHP 5-12 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Aluminum Magnesium Hydroxide",
    aliases: ["kremil-s", "maalox"],
    genericName: "AlMgOH + Simeticone",
    commonUses: "Hyperacidity, heartburn, gas",
    warnings: "Do not take within 2 hours of other meds.",
    sideEffects: ["Chalky taste", "Constipation/Diarrhea"],
    estimatedPrice: "PHP 6-10 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Phenylephrine + Paracetamol",
    aliases: ["neozep", "bioflu", "decolgen"],
    genericName: "Phenylephrine HCl + Chlorphenamine + Paracetamol",
    commonUses: "Colds, fever, runny nose",
    warnings: "May cause drowsiness. Avoid alcohol.",
    sideEffects: ["Drowsiness", "Dry mouth"],
    estimatedPrice: "PHP 6-12 per tablet",
    philHealthCovered: false,
  },
  {
    name: "Moringa",
    aliases: ["malunggay", "natalac"],
    genericName: "Moringa Oleifera",
    commonUses: "Nutritional supplement, lactation aid",
    warnings: "Safe supplement. Consult doctor if pregnant.",
    sideEffects: ["None known"],
    estimatedPrice: "PHP 5-10 per capsule",
    philHealthCovered: false,
  },
  {
    name: "Vitamins B-Complex",
    aliases: ["neurobion", "poly-nerve"],
    genericName: "Vitamin B1 + B6 + B12",
    commonUses: "Nerve health, energy",
    warnings: "Do not exceed recommended dose.",
    sideEffects: ["Bright yellow urine (harmless)"],
    estimatedPrice: "PHP 10-25 per tablet",
    philHealthCovered: false,
  },
].map(enrichOfflineMedicine);

export const ALL_OFFLINE_MEDICINES: OfflineMedicineRecord[] = OFFLINE_MEDICINES;

export function getOfflineMedicineCount(): number {
  return (
    OFFLINE_MEDICINES.length +
    getPhilippineOfflineMedicineCount() +
    getGeneratedPhilippineOfflineMedicineCount() +
    getGeneratedOfflineMedicineCount()
  );
}

export function getGeneratedOfflineMedicineCount(): number {
  return loadGeneratedMedicines().length;
}

export function getPhilippineOfflineMedicineCount(): number {
  return loadPhilippineMedicines().length;
}

export function getGeneratedPhilippineOfflineMedicineCount(): number {
  return loadGeneratedPhilippineMedicines().length;
}

export function getAllOfflineMedicines(): OfflineMedicineRecord[] {
  return loadAllOfflineMedicines();
}
